### ISSUE TITLE
Crashes on Heroku launch,

### ISSUE THREAD

**Issue by adr29truck** [adr29truck/memory-archive#17]
**Describe the bug**
Server crashes on startup.

Error log: 
```
[time-stamp] stty: 'standard input': Inappropriate ioctl for device
[time-stamp] stty: 'standard input': Inappropriate ioctl for device
```

**To Reproduce**
1. Deploy server to heroku

**Expected behavior**
Not crashing.

**Screenshots**

**Additional context**
Probably has something to with how it is executed. 
It seems as if though rake run is executed even thought the `Procfile` states production should run.

**Comment by adr29truck** [comment]
Upon closer inspection it seems as if pg is not loaded. 
```

2020-06-03T21:19:38.333869+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/adapters/postgres.rb:6:in `require': LoadError: cannot load such file -- pg (Sequel::AdapterNotFound)
2020-06-03T21:19:38.333879+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/adapters/postgres.rb:6:in `<top (required)>'
2020-06-03T21:19:38.333880+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/database/connecting.rb:88:in `require'
2020-06-03T21:19:38.333880+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/database/connecting.rb:88:in `load_adapter'
2020-06-03T21:19:38.333881+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/database/connecting.rb:17:in `adapter_class'
2020-06-03T21:19:38.333881+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/database/connecting.rb:36:in `connect'
2020-06-03T21:19:38.333882+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/core.rb:125:in `connect'
2020-06-03T21:19:38.333886+00:00 app[web.1]: 	from /app/bin/modules/application_controller.rb:13:in `<class:ApplicationController>'
2020-06-03T21:19:38.333887+00:00 app[web.1]: 	from /app/bin/modules/application_controller.rb:5:in `<top (required)>'
2020-06-03T21:19:38.333887+00:00 app[web.1]: 	from /app/bin/modules/reset_password.rb:4:in `require_relative'
2020-06-03T21:19:38.333888+00:00 app[web.1]: 	from /app/bin/modules/reset_password.rb:4:in `<top (required)>'
2020-06-03T21:19:38.333888+00:00 app[web.1]: 	from /app/config.ru:14:in `require_relative'
2020-06-03T21:19:38.333889+00:00 app[web.1]: 	from /app/config.ru:14:in `block (2 levels) in <main>'
2020-06-03T21:19:38.333889+00:00 app[web.1]: 	from /app/config.ru:13:in `each'
2020-06-03T21:19:38.333889+00:00 app[web.1]: 	from /app/config.ru:13:in `block in <main>'
2020-06-03T21:19:38.333890+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
2020-06-03T21:19:38.333890+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
2020-06-03T21:19:38.333890+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
2020-06-03T21:19:38.333891+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
2020-06-03T21:19:38.333891+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2020-06-03T21:19:38.333893+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
2020-06-03T21:19:38.333893+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
2020-06-03T21:19:38.333894+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:312:in `block in start'
2020-06-03T21:19:38.333895+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:379:in `handle_profiling'
2020-06-03T21:19:38.333896+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:311:in `start'
2020-06-03T21:19:38.333923+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:168:in `start'
2020-06-03T21:19:38.333924+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/bin/rackup:5:in `<top (required)>'
2020-06-03T21:19:38.333924+00:00 app[web.1]: 	from /app/vendor/bundle/bin/rackup:29:in `load'
2020-06-03T21:19:38.333925+00:00 app[web.1]: 	from /app/vendor/bundle/bin/rackup:29:in `<main>'
2020-06-03T21:19:38.333931+00:00 app[web.1]: /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/adapters/postgres.rb:6:in `require': cannot load such file -- pg (LoadError)
2020-06-03T21:19:38.333933+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/adapters/postgres.rb:6:in `<top (required)>'
2020-06-03T21:19:38.333935+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/database/connecting.rb:88:in `require'
2020-06-03T21:19:38.333937+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/database/connecting.rb:88:in `load_adapter'
2020-06-03T21:19:38.333939+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/database/connecting.rb:17:in `adapter_class'
2020-06-03T21:19:38.333941+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/database/connecting.rb:36:in `connect'
2020-06-03T21:19:38.333943+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/sequel-5.33.0/lib/sequel/core.rb:125:in `connect'
2020-06-03T21:19:38.333945+00:00 app[web.1]: 	from /app/bin/modules/application_controller.rb:13:in `<class:ApplicationController>'
2020-06-03T21:19:38.333948+00:00 app[web.1]: 	from /app/bin/modules/application_controller.rb:5:in `<top (required)>'
2020-06-03T21:19:38.333992+00:00 app[web.1]: 	from /app/bin/modules/reset_password.rb:4:in `require_relative'
2020-06-03T21:19:38.333993+00:00 app[web.1]: 	from /app/bin/modules/reset_password.rb:4:in `<top (required)>'
2020-06-03T21:19:38.333993+00:00 app[web.1]: 	from /app/config.ru:14:in `require_relative'
2020-06-03T21:19:38.333994+00:00 app[web.1]: 	from /app/config.ru:14:in `block (2 levels) in <main>'
2020-06-03T21:19:38.333994+00:00 app[web.1]: 	from /app/config.ru:13:in `each'
2020-06-03T21:19:38.333994+00:00 app[web.1]: 	from /app/config.ru:13:in `block in <main>'
2020-06-03T21:19:38.333995+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `eval'
2020-06-03T21:19:38.333995+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:116:in `new_from_string'
2020-06-03T21:19:38.333998+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:105:in `load_file'
2020-06-03T21:19:38.334027+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/builder.rb:66:in `parse_file'
2020-06-03T21:19:38.334029+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:349:in `build_app_and_options_from_config'
2020-06-03T21:19:38.334048+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:249:in `app'
2020-06-03T21:19:38.334049+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:422:in `wrapped_app'
2020-06-03T21:19:38.334068+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:312:in `block in start'
2020-06-03T21:19:38.334068+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:379:in `handle_profiling'
2020-06-03T21:19:38.334070+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:311:in `start'
2020-06-03T21:19:38.334093+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/lib/rack/server.rb:168:in `start'
2020-06-03T21:19:38.334094+00:00 app[web.1]: 	from /app/vendor/bundle/ruby/2.6.0/gems/rack-2.2.2/bin/rackup:5:in `<top (required)>'
2020-06-03T21:19:38.334096+00:00 app[web.1]: 	from /app/vendor/bundle/bin/rackup:29:in `load'
2020-06-03T21:19:38.334098+00:00 app[web.1]: 	from /app/vendor/bundle/bin/rackup:29:in `<main>'
2020-06-03T21:19:38.338905+00:00 app[web.1]: rake aborted!```

**Comment by adr29truck** [comment]
Resolved
